// Copyright (c) Tailscale Inc & contributors
// SPDX-License-Identifier: BSD-3-Clause

// Code generated by gen_deps.go; DO NOT EDIT.

package integration

import (
	// And depend on a bunch of tailscaled innards, for Go's test caching.
	// Otherwise cmd/go never sees that we depend on these packages'
	// transitive deps when we run "go install tailscaled" in a child
	// process and can cache a prior success when a dependency changes.
	_ "github.com/Xinlong-Wu/tailscale-oh/client/local"
	_ "github.com/Xinlong-Wu/tailscale-oh/cmd/tailscaled/childproc"
	_ "github.com/Xinlong-Wu/tailscale-oh/control/controlclient"
	_ "github.com/Xinlong-Wu/tailscale-oh/derp/derphttp"
	_ "github.com/Xinlong-Wu/tailscale-oh/drive/driveimpl"
	_ "github.com/Xinlong-Wu/tailscale-oh/envknob"
	_ "github.com/Xinlong-Wu/tailscale-oh/feature"
	_ "github.com/Xinlong-Wu/tailscale-oh/feature/buildfeatures"
	_ "github.com/Xinlong-Wu/tailscale-oh/feature/condregister"
	_ "github.com/Xinlong-Wu/tailscale-oh/feature/ssh"
	_ "github.com/Xinlong-Wu/tailscale-oh/health"
	_ "github.com/Xinlong-Wu/tailscale-oh/hostinfo"
	_ "github.com/Xinlong-Wu/tailscale-oh/ipn"
	_ "github.com/Xinlong-Wu/tailscale-oh/ipn/conffile"
	_ "github.com/Xinlong-Wu/tailscale-oh/ipn/ipnlocal"
	_ "github.com/Xinlong-Wu/tailscale-oh/ipn/ipnserver"
	_ "github.com/Xinlong-Wu/tailscale-oh/ipn/store"
	_ "github.com/Xinlong-Wu/tailscale-oh/ipn/store/mem"
	_ "github.com/Xinlong-Wu/tailscale-oh/logpolicy"
	_ "github.com/Xinlong-Wu/tailscale-oh/logtail"
	_ "github.com/Xinlong-Wu/tailscale-oh/net/dns"
	_ "github.com/Xinlong-Wu/tailscale-oh/net/dnsfallback"
	_ "github.com/Xinlong-Wu/tailscale-oh/net/netmon"
	_ "github.com/Xinlong-Wu/tailscale-oh/net/netns"
	_ "github.com/Xinlong-Wu/tailscale-oh/net/proxymux"
	_ "github.com/Xinlong-Wu/tailscale-oh/net/socks5"
	_ "github.com/Xinlong-Wu/tailscale-oh/net/tsdial"
	_ "github.com/Xinlong-Wu/tailscale-oh/net/tstun"
	_ "github.com/Xinlong-Wu/tailscale-oh/paths"
	_ "github.com/Xinlong-Wu/tailscale-oh/safesocket"
	_ "github.com/Xinlong-Wu/tailscale-oh/syncs"
	_ "github.com/Xinlong-Wu/tailscale-oh/tailcfg"
	_ "github.com/Xinlong-Wu/tailscale-oh/tsd"
	_ "github.com/Xinlong-Wu/tailscale-oh/tsweb/varz"
	_ "github.com/Xinlong-Wu/tailscale-oh/types/flagtype"
	_ "github.com/Xinlong-Wu/tailscale-oh/types/key"
	_ "github.com/Xinlong-Wu/tailscale-oh/types/logger"
	_ "github.com/Xinlong-Wu/tailscale-oh/types/logid"
	_ "github.com/Xinlong-Wu/tailscale-oh/util/clientmetric"
	_ "github.com/Xinlong-Wu/tailscale-oh/util/eventbus"
	_ "github.com/Xinlong-Wu/tailscale-oh/util/osshare"
	_ "github.com/Xinlong-Wu/tailscale-oh/util/syspolicy"
	_ "github.com/Xinlong-Wu/tailscale-oh/util/syspolicy/pkey"
	_ "github.com/Xinlong-Wu/tailscale-oh/util/syspolicy/policyclient"
	_ "github.com/Xinlong-Wu/tailscale-oh/version"
	_ "github.com/Xinlong-Wu/tailscale-oh/version/distro"
	_ "github.com/Xinlong-Wu/tailscale-oh/wgengine"
	_ "github.com/Xinlong-Wu/tailscale-oh/wgengine/netstack"
	_ "github.com/Xinlong-Wu/tailscale-oh/wgengine/router"
)
